housem/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework import serializers, viewsets, routers, permissions
from rest_framework import status
from tsj.models import *
from django.conf import settings
from django.conf.urls.static import static


# Serializers define the API representation.
class CompanySerializer(serializers.HyperlinkedModelSerializer):

    class Meta:
        model = Company
        fields = ('company_type', 'full_name','post_address','phone','email','boss_fio',
        	'inn','orgn','orgn_date','orgn_emitter','kpp','bill_numb',
        	'bank_name','kor_schet','bik','workgraph')

class CompanyViewSet(viewsets.ModelViewSet):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer
    # permission_classes = (permissions.IsAuthenticated, )

class ResidentSerializer(serializers.HyperlinkedModelSerializer):
    user = serializers.PrimaryKeyRelatedField()
    house = serializers.RelatedField()

    class Meta:
        model = Resident
        fields = ('first_name', 'last_name', 'middle_name', 'flat', 'bill_numb', 'phone', 'user', 'house')

class ResidentViewSet(viewsets.ModelViewSet):
    queryset = Resident.objects.all()
    serializer_class = ResidentSerializer
    # permission_classes = (permissions.IsAuthenticated,)


class MeterSerializer(serializers.HyperlinkedModelSerializer):
    meter_type = serializers.PrimaryKeyRelatedField()

    class Meta:
        model = MeterReadingHistory


class MeterViewSet(viewsets.ModelViewSet):
    queryset = MeterReadingHistory.objects.all()
    serializer_class = MeterSerializer


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'company', CompanyViewSet)
router.register(r'user', ResidentViewSet)
router.register(r'meter', MeterViewSet)

urlpatterns = patterns('',

    url(r'^api/', include(router.urls)),
    url(r'^api/auth/$', 'tsj.views.auth_api', name="auth_api"),
    url(r'^api/news/(?P<company_id>\d+)/$', 'tsj.views.news_api', name="news_api"),
    url(r'^$', 'tsj.views.home', name='home'),
    url(r'^org/home/$', 'tsj.views.orghome', name="orghome"),
    url(r'^org/profile/$', 'tsj.views.orgprofile', name="orgprofile"),
    url(r'^profile/$', 'tsj.views.userprofile', name="userprofile"),
    url(r'^auth/$', 'tsj.views.auth', name='auth'),
    url(r'^logout/$', 'tsj.views.logoutview', name='logoutview'),
    url(r'^registration/$', 'tsj.views.registration', name="registration"),
    url(r'^register/$', 'tsj.views.register', name="register"),
    url(r'^org/registration/$', 'tsj.views.orgregistration', name="orgregistration"),
    url(r'^org/houses/$', 'tsj.views.list_houses', name="list_houses"),
    url(r'^org/services/$', 'tsj.views.add_services', name="add_services"),
    url(r'^org/houses/delete/$', 'tsj.views.delete_house', name="delete_house"),
    url(r'^org/houses/add/$', 'tsj.views.add_house', name="add_houses"),
    url(r'^org/create_notification/$', 'tsj.views.create_notification', name="create_notification"),
    url(r'^org/delete_notification/$', 'tsj.views.delete_notification', name="delete_notification"),
    url(r'^org/residents/$', 'tsj.views.list_residents', name="list_residents"),
    url(r'^org/residents/delete/$', 'tsj.views.delete_resident', name="delete_resident"),
    url(r'^org/approve/$', 'tsj.views.userapprove', name="userapprove"),
    url(r'^org/add_services/$', 'tsj.views.add_services', name="add_services"),
    url(r'^org/delete_services/$', 'tsj.views.delete_services', name="delete_services"),
    url(r'^org/add_employer/$', 'tsj.views.add_employer', name="add_employer"),
    url(r'^org/delete_employer/$', 'tsj.views.delete_employer', name="delete_employer"),
    url(r'^org/sendwelcome/(?P<pk>\d+)/$', 'tsj.views.sendwelcome', name="sendwelcome"),
    url(r'^org/sendreject/(?P<pk>\d+)/$', 'tsj.views.sendreject', name="sendreject"),
    url(r'^meter/$', 'tsj.views.meter', name="meter"),
    url(r'^org/houseaccount/(?P<pk>\d+)/$', 'tsj.views.house_account', name="houseaccount"),
    url(r'^employer_request/$', 'tsj.views.employer_request', name="employer_request"),
    url(r'^org/employer_request/$', 'tsj.views.org_employer_request', name="org_employer_request"),
    url(r'^org/delete_emp_req/(?P<pk>\d+)/$', 'tsj.views.delete_emp_req', name="delete_emp_req"),
    url(r'^org/approve_emp_req/(?P<pk>\d+)/$', 'tsj.views.approve_emp_req', name="approve_emp_req"),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tsj/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.core.validators import MinValueValidator
from .streets import STREET_CHOICES


class House(models.Model):
    street = models.IntegerField(choices=STREET_CHOICES, verbose_name=u'Улица')
    number = models.CharField(max_length=4, verbose_name=u'Номер дома')

    def __unicode__(self):
        return '%s, %s' % (self.get_street_display(), self.number)


class HouseAccount(models.Model):
    house = models.ForeignKey(House)
    account_change = models.FloatField(verbose_name=u"Величина изменения")
    pub_date = models.DateField(default=datetime.now, verbose_name=u"Дата публикации")


class BaseCompany(models.Model):
    name = models.CharField(max_length=150, verbose_name=u"Название")
    full_name = models.CharField(max_length=150, verbose_name=u"Полное наимаенование")
    post_address = models.TextField(verbose_name=u"Почтовый адрес")
    legal_address = models.TextField(verbose_name=u"Юридический адрес")
    phone = models.CharField(max_length=15, verbose_name=u"Телефон")
    email = models.EmailField(verbose_name=u"E-mail")
    boss_fio = models.CharField(max_length=50, verbose_name=u"ФИО руководителя")
    inn = models.CharField(max_length=15, verbose_name=u"ИНН")
    orgn = models.CharField(max_length=15, verbose_name=u"ОРГН")
    orgn_date = models.CharField(max_length=15, verbose_name=u"Дата выдачи ОРГН")
    orgn_emitter = models.CharField(max_length=50, verbose_name=u"Кем выдан ОРГН")
    kpp = models.CharField(max_length=15, verbose_name=u"КПП")
    bill_numb = models.CharField(max_length=15, verbose_name=u"Расчетный счет")
    bank_name = models.CharField(max_length=150, verbose_name=u"В ОАО Банк")
    kor_schet = models.CharField(max_length=15, verbose_name=u"Кор. счет")
    bik = models.CharField(max_length=15, verbose_name=u"БИК")
    workgraph = models.TextField(verbose_name=u"График работы")

    def __unicode__(self):
        return self.name

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.name


class Company(BaseCompany):
    TYPIES = (
        (0, u"ТСЖ"),
        (1, u"УК")
    )
    user = models.OneToOneField(User)
    houses = models.ManyToManyField(House)
    company_type = models.IntegerField(choices=TYPIES, default=0, verbose_name=u"Тип")
    proof = models.FileField(upload_to="scans", verbose_name=u"Подтверждающий документ")
    services = models.ManyToManyField("ServiceCompany", related_name="%(app_label)s_%(class)s_related")

    def get_company_type(self):
        return dict(self.TYPIES)[self.company_type]

    def get_residents(self):
        return Resident.objects.filter(house__id__in=self.houses.all())


class ServiceCompany(BaseCompany):
    pass


class Resident(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=15, verbose_name=u"Телефон")
    first_name = models.CharField(max_length=150, verbose_name=u"Имя")
    last_name = models.CharField(max_length=150, verbose_name=u"Фамилия")
    middle_name = models.CharField(max_length=150, verbose_name=u"Отчество")
    house = models.ForeignKey(House, verbose_name=u"Улица")
    flat = models.CharField(max_length=10, verbose_name=u"Номер квартиры")
    bill_numb = models.CharField(max_length=20, verbose_name=u"Номер лицевого счёта")
    passport = models.FileField(upload_to="scans", verbose_name=u"Скан паспорта")
    registration = models.FileField(upload_to="scans", verbose_name=u"Скан прописки")

    def __unicode__(self):
        return u"%s %s (%s, кв. %s)" % (self.first_name, self.last_name, self.house, self.flat)


class MeterType(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"Название")
    measurment = models.CharField(max_length=20, verbose_name=u"Измеряется в")

    def __unicode__(self):
        return self.name


class Employer(models.Model):
    phone = models.CharField(max_length=15, verbose_name=u"Телефон")
    first_name = models.CharField(max_length=150, verbose_name=u"Имя")
    last_name = models.CharField(max_length=150, verbose_name=u"Фамилия")
    middle_name = models.CharField(max_length=150, verbose_name=u"Отчество")
    profession = models.CharField(max_length=100, verbose_name=u"Профессия")
    company = models.ForeignKey(Company, verbose_name=u"Компания")

    def __unicode__(self):
        return u"%s %s %s" % (self.profession, self.first_name, self.last_name)


class EmployerRequest(models.Model):
    employer = models.ForeignKey(Employer)
    user = models.ForeignKey(Resident)
    request_date = models.DateField(verbose_name=u"Когда сотруднику следует прийти")
    reason = models.TextField(verbose_name=u"Причина вызова сотрудника")
    status = models.BooleanField(default=False, verbose_name=u"Статус")

    def __unicode__(self):
        return u"%s - %s, %s" % (self.employer, self.reason, self.request_date)


class MeterReadingHistory(models.Model):
    resident = models.ForeignKey(Resident)
    value = models.IntegerField(verbose_name=u"Значение",
        validators = [
            MinValueValidator(1)
        ])
    adding_date = models.DateField(default=datetime.now, verbose_name=u"Дата снятия показаний")
    meter_type = models.ForeignKey(MeterType)

    def __unicode__(self):
        return u"%s - %s" % (self.resident.last_name, self.value)


class Notification(models.Model):
    NOTIFICATIONS = (
        (0, u"Отключение воды"),
        (1, u"Отключение света"),
        (2, u"Собрание"),
        (3, u"Общее"),
    )
    NOTIFICATIONS_DICT = dict(NOTIFICATIONS)
    start_date = models.DateTimeField(verbose_name=u'Начиная с')
    end_date = models.DateTimeField(verbose_name=u'Заканчивая')
    text = models.TextField(verbose_name=u"Доп информация")
    note_type = models.IntegerField(choices=NOTIFICATIONS, default=3, verbose_name=u"Тип")
    houses = models.ManyToManyField(House)

templates/org/add_services.html
{% extends "base.html" %}
{% block menu %}
{% include "org/menu.html" %}
{% endblock %}
{% block content %}
{% include "org/leftmenu.html" %}
<div class="col-md-4">
    <h1>Подрядчики</h1>
    <table class="table table-bordered">
    {% for service in services %}
    <tr>
        <td><form action="{% url "delete_services" %}" class="pull-right" method="POST">{% csrf_token %}<input type="hidden" name="service" value="{{service.id}}"><button type="submit" class="btn btn-danger">Удалить</button></form>{{service.name}}</td>
    </tr>
    {% endfor %}
    </table>

    <form class="form-inline" action="{% url "add_services" %}" method="POST" role="form">{% csrf_token %}
        <div class="form-group">
            <label class="sr-only" for="house">Дом</label>
            {{form.service}}
        </div>
        <button type="submit" class="btn btn-default">Добавить подрядчика</button>
    </form>
</div>
<div class="col-md-4">
    <h1>Сотрудники</h1>

    <table class="table table-bordered">
    {% for employer in employers %}
    <tr>
        <td><form action="{% url "delete_employer" %}" class="pull-right" method="POST">{% csrf_token %}<input type="hidden" name="employer" value="{{employer.id}}"><button type="submit" class="btn btn-danger">Удалить</button></form>{{employer}}<br><small><i>{{employer.phone}}, {{employer.profession}}</i></small></td>
    </tr>
    {% endfor %}
    </table>
    <form method = "post" action="{% url "add_employer" %}" enctype="multipart/form-data" class="form-horizontal" role="form">
    {% csrf_token %}
     <div class="form-group">
        <div class="col-sm-offset-3 col-sm-10">

        {% for field in emplform.visible_fields %}
        <div class="form-group {% if field.errors %}has-error{% endif %}">
            <label for="{{field.name}}" class="col-sm-3 control-label">{{field.label}}:</label>
            <div class="col-sm-8">
                {{field}}       <span class="help-block">{% if field.errors %}{% for error in field.errors %}{{error}}{% endfor %}{% endif %}</span>

            </div>
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-success">Добавить</button>
     </div>
    </form>

</div>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $("form input, form textarea, form select").addClass("form-control");
        $('input[type=file]')
            .addClass("btn-primary")
            .attr('title', "Добавить документ")
            .attr('data-filename-placement', "inside")
            .bootstrapFileInput();

    </script>
{% endblock %}

templates/org/employer_request.html
{% extends "base.html" %}

{% block menu %}
{% include "org/menu.html" %}
{% endblock %}

{% block content %}

{% include "org/leftmenu.html" %}

<h2>Список заявок</h2>

<div class="col-md-10">

  {% if hist %}
  <table class="table">
   <thead>
   		<tr> 
   			<th>№</th>
   			{# <th>ФИО</th> #}
   			<th>Работник</th>
   			<th>Причина вызова</th>
   			<th>Статус</th>
   		</tr>
   </thead>
   <tbody>
   		{% for h in hist %}
      <tr>
   			<td>{{ forloop.counter }}</td>
   			<td>{{ h.employer.profession}}</td>
   			<td>{{h.reason}}</td>
   			<td>

   			{% if h.status %}
   				Одобрено
   			{% else %}
          <div class="btn-group">
          <a href="{% url 'approve_emp_req' h.id %}">
            <button class="btn btn-success">Одобрить</button>
          </a>
            <a href="{% url 'delete_emp_req' h.id %}">
              <button class="btn btn-danger">Удалить</button>
            </a>
            
          </div>
   				
   			{% endif%}
   			</td>
   		{% endfor %}
      </tr>
   </tbody>
  </table>

  {% else %}
  	Нет заявок
  {% endif%}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(function() {
  $( "#request_date" ).datepicker({
    defaultDate: "0",
    minDate:"0",
    altFormat: "yy-mm-dd",
    dateFormat: "yy-mm-dd",
    changeMonth: true,
    onClose: function( selectedDate ) {
      $( "#to" ).datepicker( "option", "minDate", selectedDate );
    }
  });
});
</script>
{% endblock %}

templates/org/home.html
{% extends "base.html" %}
{% block menu %}
{% include "org/menu.html" %}
{% endblock %}
{% block content %}
{% include "org/leftmenu.html" %}
{% endblock %}

templates/org/house_account.html
{% extends "base.html" %}
{% block menu %}
{% include "org/menu.html" %}
{% endblock %}
{% block content %}
{% include "org/leftmenu.html" %}

<h2>Ввод изменений счёта дома</h2>
	<div class="col-md-10">
  <div class="jumbotron">
 
		<form method = "post"  action="{% url "houseaccount" pk %}" enctype="multipart/form-data"  class="form-horizontal" role="form">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	<div class="form-group {% if field.errors %}has-error{% endif %}">
		<label for="{{field.name}}" class="col-sm-3 control-label">{{field.label}}:</label>
		<div class="col-sm-4">
			{{field}}		<span class="help-block">{% if field.errors %}{% for error in field.errors %}{{error}}{% endfor %}{% endif %}</span>

		</div>
	</div>
	{% endfor %}
	 <div class="form-group">
	    <div class="col-sm-offset-3 col-sm-10">
	    	<button type="submit" class="btn btn-success">Ввести</button>
	    </div>
	 </div>
	</form>
      </div>
  <h2>История счета</h2>
  {% if hist %}
  <table class="table">
   <thead>
   		<tr> 
   			<th>№</th>
   			<th>Значение</th>
   			<th>Дата</th>
   		</tr>
   </thead>
   <tbody>
   		{% for h in hist %}
      <tr>
   			<td>{{ forloop.counter }}</td>
   			<td>{{h.account_change}}</td>
   			<td>{{h.pub_date}}</td>
   		{% endfor %}
      </tr>
   </tbody>
  </table>
<hr style="border: 1px solid #000;" size="30"> 
<p><h3>Итого: {{sum}}</h3></p>
</div>

  {% else %}
  	Нет данных
  {% endif%}

</div>
	

{% endblock %}

templates/org/houses.html
{% extends "base.html" %}
{% block menu %}
{% include "org/menu.html" %}
{% endblock %}
{% block content %}
{% include "org/leftmenu.html" %}
<div class="col-md-8">
    <table class="table table-striped">
   
    <thead>
        <tr>
            <th>Дом</th>
            <th>Управление</th>
        </tr>
    </thead>
    <tbody>
     {% for house in houses %}
    <tr>
        <td>{{house}}</td>
        <td>

        <div class="btn-group">
    
        
            <form action="{% url "delete_house" %}" method="POST">{% csrf_token %}<input type="hidden" name="house" value="{{house.id}}">
        <a href="{% url 'houseaccount' house.id %}">
        <button type="button" class="btn btn-default">
        <span class="glyphicon glyphicon-euro"></span></button></a>
            <button type="submit" class="btn btn-danger">Удалить</button>
            </form>

        
        </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>

    </table>
    Пока нет ни одного дома. Вы можете добавить управляемые дома ниже

<div class="container col-md-8">
<form class="form-horizontal" action="{% url "add_houses" %}" method="POST" role="form">{% csrf_token %}
    <div class="row">
        <div class = "col-md-6">
            <div class="form-group">
                <label class="sr-only" for="street">Улица</label>
                {{form.street}}
            </div>
        </div>
        <div class = "col-md-2">
            <div class="form-group">
                <label class="sr-only" for="number">номер дома</label>
                {{form.number}}
            </div>
        </div>
        <div class = "col-md-4">
            <div class="form-group">
                <button type="submit" class="btn btn-default">Добавить дом</button>
            </div>
        </div>
    </div>
</form>
</div>

</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
    $("#id_number").addClass("form-control").attr("placeholder", "дом");
    $("#id_street").select2({"placeholder": "Выберите дом"});

</script>
{% endblock %}

templates/org/leftmenu.html
<div class="col-md-2">
<ul class="nav nav-pills nav-stacked">
    <li {% if current_url == "list_houses" %}class="active"{% endif %}><a href="{% url "list_houses" %}">Список домов</a></li>
    <li {% if current_url == "list_residents" %}class="active"{% endif %}><a href="{% url "list_residents" %}">Список жильцов</a></li>
    <li {% if current_url == "add_services" %}class="active"{% endif %}><a href="{% url "add_services" %}">Сотрудники и подрячики</a></li>
    <li {% if current_url == "create_notification" %}class="active"{% endif %}><a href="{% url "create_notification" %}">Создать оповещение</a></li>
    <li><a href="{% url 'userapprove' %}"><span class="label label-success pull-right">
    {{regcounter}}</span>Запросы на регистрацию </a></li>
    <li><a href="{% url 'org_employer_request' %}">Заявки на сотрудников</a></li>
    <li><a href="#">Показания счётчиков </a></li>
    <li><a href="#">Вывод по счетам</a></li>
</ul>
</div>

templates/org/menu.html
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url "home" %}">House Management</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li {% if current_url == "orgprofile" %} class="active" {% endif %}><a href="{% url "orgprofile" %}">Профиль</a></li>
                <li ><a href="{% url "logoutview" %}">Выход</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

templates/org/notify.html
{% extends "base.html" %}
{% block menu %}
{% include "org/menu.html" %}
{% endblock %}
{% block content %}
{% include "org/leftmenu.html" %}
<div class="col-md-10">
<table class="table table-bordered">
{% for notify in notifies %}
<tr>
    <td>{{notify.text}}</td>
    <td>{{notify.start_date|date:"j E"}} по {{notify.end_date|date:"j E"}}</td>
    <td>{% for house in notify.houses.all %}{{house}}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
    <td><form action="{% url "delete_notification" %}" method="POST">{% csrf_token %}<input type="hidden" name="notify" value="{{notify.id}}"><button type="submit" class="btn btn-danger">Удалить</button></form></td>
</tr>
{% endfor %}
</table>
<form role="form" method="POST">
{% csrf_token %}
<div class="btn-group" data-toggle="buttons">
  <label class="btn btn-default active">
    <input type="radio" name="note_type" value="0" checked> Отключение воды
  </label>
  <label class="btn btn-default">
    <input type="radio" name="note_type" value="1"> Отключение света
  </label>
  <label class="btn btn-default">
    <input type="radio" name="note_type" value="2"> Собрание
  </label>
  <label class="btn btn-default">
    <input type="radio" name="note_type" value="3"> Другое
  </label>
</div>
  <div class="form-group">
    <label for="text">Отправить жильцам домов:</label>
    <select id="houses"  multiple class="form-control" name="houses">
        {% for house in houses %}
        <option value="{{house.id}}">{{house}}</option>
        {% endfor %}
    </select>
  </div>
  <div class="form-group">
    <label for="text">Начиная с:</label>
    <div class="input-group col-sm-3" >
      <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
      <input class="form-control" id="from" name="start_date" placeholder="введите нач. дату">
    </div>
  </div>
  <div class="form-group">
    <label for="text">Заканчивая:</label>
    <div class="input-group col-sm-3" >
      <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
      <input class="form-control" id="to" name="end_date" placeholder="введите кон. дату">
    </div>
  </div>
  <div class="form-group">
    <label for="text">Текст</label>
    <textarea type="email" class="form-control" name="text" id="text" placeholder="Например, время"></textarea>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-success">Отправить</button>
  </div>
</form>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$(function() {
  $( "#from" ).datepicker({
    defaultDate: "0",
    minDate:"0",
    altFormat: "dd.mm.yy",
    dateFormat: "dd.mm.yy",
    changeMonth: true,
    onClose: function( selectedDate ) {
      $( "#to" ).datepicker( "option", "minDate", selectedDate );
    }
  });
  $( "#to" ).datepicker({
    defaultDate: "+0",
    altFormat: "dd.mm.yy",
    dateFormat: "dd.mm.yy",
    changeMonth: true,
    onClose: function( selectedDate ) {
      $( "#from" ).datepicker( "option", "maxDate", selectedDate );
    }
  });
});
</script>
{% endblock %}

templates/org/profile.html
{% extends "base.html" %}
{% block menu %}
{% include "org/menu.html" %}
{% endblock %}
{% block content %}
{% include "org/leftmenu.html" %}
<div class="col-md-10">
    <table class="table table-bordered">
    {% for field in profile %}
    {% if field.value %}
    <tr>
        <td>{{field.label}}</td>
        <td>{{field.value}}</td>
    </tr>
    {% endif %}
    {% endfor %}
    </table>
</div>
{% endblock %}

templates/org/registration.html
{% extends "base.html" %}
{% comment %}
	ФИО
	Л/С (реквизит квартиры)
	Доки (аттач: паспорт и прописка)
	Телефон
{% endcomment %}
{% block scripts %}
	<script type="text/javascript">
		$("form input, form textarea, form select").addClass("form-control");
		$('input[type=file]')
			.addClass("btn-primary")
			.attr('title', "Добавить документ")
			.attr('data-filename-placement', "inside")
			.bootstrapFileInput();

	</script>
{% endblock %}
{% block content %}


	<form method = "post" action="{% url "orgregistration" %}" enctype="multipart/form-data" class="form-horizontal" role="form">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	<div class="form-group {% if field.errors %}has-error{% endif %}">
		<label for="{{field.name}}" class="col-sm-3 control-label">{{field.label}}:</label>
		<div class="col-sm-4">
			{{field}}		<span class="help-block">{% if field.errors %}{% for error in field.errors %}{{error}}{% endfor %}{% endif %}</span>

		</div>
	</div>
	{% endfor %}
	 <div class="form-group">
	    <div class="col-sm-offset-3 col-sm-10">
	    <button type="submit" class="btn btn-success">Регистрация</button>
	 </div>
	</form>
{% endblock %}

templates/org/residents.html
{% extends "base.html" %}
{% block menu %}
{% include "org/menu.html" %}
{% endblock %}
{% block content %}
{% include "org/leftmenu.html" %}
<div class="col-md-10">
    <table class="table table-bordered">
    {% for resident in residents %}
    <tr>
        <td>{{resident.first_name}}{{resident.last_name}}</td>
        <td>{{resident.house}}, кв. {{resident.flat}}</td>
        <td><form action="{% url "delete_resident" %}" method="POST">{% csrf_token %}<input type="hidden" name="resident" value="{{resident.id}}"><button type="submit" class="btn btn-danger">Удалить</button></form></td>
    </tr>
    {% endfor %}
    </table>

</div>
{% endblock %}

templates/org/user_approve.html
{% extends "base.html" %}

{% block menu %}
{% include "org/menu.html" %}
{% endblock %}

{% block content %}
	
{% include "org/leftmenu.html" %}
<div class="col-md-10">
	<h3>Пользователи на рассмотрении</h3>
	<div class="table-responsive">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th>ФИО</th>
                  <th>Дом</th>
                  <th>Паспорт</th>
                  <th>Прописка</th>
                  <th>Решение</th>
                </tr>
              </thead>
              <tbody>
  				{% for u in users %}
  					<tr>
  						<td>{{ u.last_name }} {{ u.first_name }} {{ u.middle_name }}</td>
  						<td>{{ u.house }}, кв. {{ u.flat }}</td>
  						<td>
	  						<a href="{{ u.passport.url }}" data-lightbox="doc" data-title="Паспорт" >
	  							<img src="{{ u.passport.url }}" style="max-width:100%;max-height:200px;">
	  						</a>
  						</td>
  						<td>
  							<a href="{{ u.registration.url }}"  data-lightbox="doc" data-title="Прописка">
	  							<img src="{{ u.registration.url }}"  style="max-width:100%;max-height:200px;">
	  						</a>
  						</td>
  						<td> 
  						<a href="{% url "sendwelcome" u.id %}">
  							<button type="button" class="btn btn-success">Одобрить</button>
  						</a>
  							
						<a href="{% url "sendreject" u.id %}">
							<button type="button" class="btn btn-danger">Отклонить</button>
						</a>
  							
  						</td>
  					</tr>
				{% endfor%}
              </tbody>
            </table>
          </div>
</div>
{% endblock %}
{% block style %}
<link href="{{STATIC_URL}}css/lightbox.css" rel="stylesheet" />
{% endblock %}
{% block scripts %}
<script src="{{STATIC_URL}}js/jquery-1.11.0.min.js"></script>
<script src="{{STATIC_URL}}js/lightbox.min.js"></script>
{% endblock %}