housem/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from rest_framework import serializers, viewsets, routers, permissions
from rest_framework import status
from tsj.models import *
from django.conf import settings
from django.conf.urls.static import static


# Serializers define the API representation.
class CompanySerializer(serializers.HyperlinkedModelSerializer):

    class Meta:
        model = Company
        fields = ('company_type', 'full_name','post_address','phone','email','boss_fio',
        	'inn','orgn','orgn_date','orgn_emitter','kpp','bill_numb',
        	'bank_name','kor_schet','bik','workgraph')

class CompanyViewSet(viewsets.ModelViewSet):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer
    # permission_classes = (permissions.IsAuthenticated, )

class ResidentSerializer(serializers.HyperlinkedModelSerializer):
    user = serializers.PrimaryKeyRelatedField()
    house = serializers.RelatedField()

    class Meta:
        model = Resident
        fields = ('first_name', 'last_name', 'middle_name', 'flat', 'bill_numb', 'phone', 'user', 'house')

class ResidentViewSet(viewsets.ModelViewSet):
    queryset = Resident.objects.all()
    serializer_class = ResidentSerializer
    # permission_classes = (permissions.IsAuthenticated,)


class MeterSerializer(serializers.HyperlinkedModelSerializer):
    meter_type = serializers.PrimaryKeyRelatedField()

    class Meta:
        model = MeterReadingHistory


class MeterViewSet(viewsets.ModelViewSet):
    queryset = MeterReadingHistory.objects.all()
    serializer_class = MeterSerializer


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'company', CompanyViewSet)
router.register(r'user', ResidentViewSet)
router.register(r'meter', MeterViewSet)

urlpatterns = patterns('',

    url(r'^api/', include(router.urls)),
    url(r'^api/auth/$', 'tsj.views.auth_api', name="auth_api"),
    url(r'^api/news/(?P<company_id>\d+)/$', 'tsj.views.news_api', name="news_api"),
    url(r'^$', 'tsj.views.home', name='home'),
    url(r'^org/home/$', 'tsj.views.orghome', name="orghome"),
    url(r'^org/profile/$', 'tsj.views.orgprofile', name="orgprofile"),
    url(r'^profile/$', 'tsj.views.userprofile', name="userprofile"),
    url(r'^auth/$', 'tsj.views.auth', name='auth'),
    url(r'^logout/$', 'tsj.views.logoutview', name='logoutview'),
    url(r'^registration/$', 'tsj.views.registration', name="registration"),
    url(r'^register/$', 'tsj.views.register', name="register"),
    url(r'^org/registration/$', 'tsj.views.orgregistration', name="orgregistration"),
    url(r'^org/houses/$', 'tsj.views.list_houses', name="list_houses"),
    url(r'^org/services/$', 'tsj.views.add_services', name="add_services"),
    url(r'^org/houses/delete/$', 'tsj.views.delete_house', name="delete_house"),
    url(r'^org/houses/add/$', 'tsj.views.add_house', name="add_houses"),
    url(r'^org/create_notification/$', 'tsj.views.create_notification', name="create_notification"),
    url(r'^org/delete_notification/$', 'tsj.views.delete_notification', name="delete_notification"),
    url(r'^org/residents/$', 'tsj.views.list_residents', name="list_residents"),
    url(r'^org/residents/delete/$', 'tsj.views.delete_resident', name="delete_resident"),
    url(r'^org/approve/$', 'tsj.views.userapprove', name="userapprove"),
    url(r'^org/add_services/$', 'tsj.views.add_services', name="add_services"),
    url(r'^org/delete_services/$', 'tsj.views.delete_services', name="delete_services"),
    url(r'^org/add_employer/$', 'tsj.views.add_employer', name="add_employer"),
    url(r'^org/delete_employer/$', 'tsj.views.delete_employer', name="delete_employer"),
    url(r'^org/sendwelcome/(?P<pk>\d+)/$', 'tsj.views.sendwelcome', name="sendwelcome"),
    url(r'^org/sendreject/(?P<pk>\d+)/$', 'tsj.views.sendreject', name="sendreject"),
    url(r'^meter/$', 'tsj.views.meter', name="meter"),
    url(r'^org/houseaccount/(?P<pk>\d+)/$', 'tsj.views.house_account', name="houseaccount"),
    url(r'^employer_request/$', 'tsj.views.employer_request', name="employer_request"),
    url(r'^org/employer_request/$', 'tsj.views.org_employer_request', name="org_employer_request"),
    url(r'^org/delete_emp_req/(?P<pk>\d+)/$', 'tsj.views.delete_emp_req', name="delete_emp_req"),
    url(r'^org/approve_emp_req/(?P<pk>\d+)/$', 'tsj.views.approve_emp_req', name="approve_emp_req"),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += patterns('',
        url(r'^__debug__/', include(debug_toolbar.urls)),
    )
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tsj/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.core.validators import MinValueValidator
from .streets import STREET_CHOICES


class House(models.Model):
    street = models.IntegerField(choices=STREET_CHOICES, verbose_name=u'Улица')
    number = models.CharField(max_length=4, verbose_name=u'Номер дома')

    def __unicode__(self):
        return '%s, %s' % (self.get_street_display(), self.number)


class HouseAccount(models.Model):
    house = models.ForeignKey(House)
    account_change = models.FloatField(verbose_name=u"Величина изменения")
    pub_date = models.DateField(default=datetime.now, verbose_name=u"Дата публикации")


class BaseCompany(models.Model):
    name = models.CharField(max_length=150, verbose_name=u"Название")
    full_name = models.CharField(max_length=150, verbose_name=u"Полное наимаенование")
    post_address = models.TextField(verbose_name=u"Почтовый адрес")
    legal_address = models.TextField(verbose_name=u"Юридический адрес")
    phone = models.CharField(max_length=15, verbose_name=u"Телефон")
    email = models.EmailField(verbose_name=u"E-mail")
    boss_fio = models.CharField(max_length=50, verbose_name=u"ФИО руководителя")
    inn = models.CharField(max_length=15, verbose_name=u"ИНН")
    orgn = models.CharField(max_length=15, verbose_name=u"ОРГН")
    orgn_date = models.CharField(max_length=15, verbose_name=u"Дата выдачи ОРГН")
    orgn_emitter = models.CharField(max_length=50, verbose_name=u"Кем выдан ОРГН")
    kpp = models.CharField(max_length=15, verbose_name=u"КПП")
    bill_numb = models.CharField(max_length=15, verbose_name=u"Расчетный счет")
    bank_name = models.CharField(max_length=150, verbose_name=u"В ОАО Банк")
    kor_schet = models.CharField(max_length=15, verbose_name=u"Кор. счет")
    bik = models.CharField(max_length=15, verbose_name=u"БИК")
    workgraph = models.TextField(verbose_name=u"График работы")

    def __unicode__(self):
        return self.name

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.name


class Company(BaseCompany):
    TYPIES = (
        (0, u"ТСЖ"),
        (1, u"УК")
    )
    user = models.OneToOneField(User)
    houses = models.ManyToManyField(House)
    company_type = models.IntegerField(choices=TYPIES, default=0, verbose_name=u"Тип")
    proof = models.FileField(upload_to="scans", verbose_name=u"Подтверждающий документ")
    services = models.ManyToManyField("ServiceCompany", related_name="%(app_label)s_%(class)s_related")

    def get_company_type(self):
        return dict(self.TYPIES)[self.company_type]

    def get_residents(self):
        return Resident.objects.filter(house__id__in=self.houses.all())


class ServiceCompany(BaseCompany):
    pass


class Resident(models.Model):
    user = models.OneToOneField(User)
    phone = models.CharField(max_length=15, verbose_name=u"Телефон")
    first_name = models.CharField(max_length=150, verbose_name=u"Имя")
    last_name = models.CharField(max_length=150, verbose_name=u"Фамилия")
    middle_name = models.CharField(max_length=150, verbose_name=u"Отчество")
    house = models.ForeignKey(House, verbose_name=u"Улица")
    flat = models.CharField(max_length=10, verbose_name=u"Номер квартиры")
    bill_numb = models.CharField(max_length=20, verbose_name=u"Номер лицевого счёта")
    passport = models.FileField(upload_to="scans", verbose_name=u"Скан паспорта")
    registration = models.FileField(upload_to="scans", verbose_name=u"Скан прописки")

    def __unicode__(self):
        return u"%s %s (%s, кв. %s)" % (self.first_name, self.last_name, self.house, self.flat)


class MeterType(models.Model):
    name = models.CharField(max_length=100, verbose_name=u"Название")
    measurment = models.CharField(max_length=20, verbose_name=u"Измеряется в")

    def __unicode__(self):
        return self.name


class Employer(models.Model):
    phone = models.CharField(max_length=15, verbose_name=u"Телефон")
    first_name = models.CharField(max_length=150, verbose_name=u"Имя")
    last_name = models.CharField(max_length=150, verbose_name=u"Фамилия")
    middle_name = models.CharField(max_length=150, verbose_name=u"Отчество")
    profession = models.CharField(max_length=100, verbose_name=u"Профессия")
    company = models.ForeignKey(Company, verbose_name=u"Компания")

    def __unicode__(self):
        return u"%s %s %s" % (self.profession, self.first_name, self.last_name)


class EmployerRequest(models.Model):
    employer = models.ForeignKey(Employer)
    user = models.ForeignKey(Resident)
    request_date = models.DateField(verbose_name=u"Когда сотруднику следует прийти")
    reason = models.TextField(verbose_name=u"Причина вызова сотрудника")
    status = models.BooleanField(default=False, verbose_name=u"Статус")

    def __unicode__(self):
        return u"%s - %s, %s" % (self.employer, self.reason, self.request_date)


class MeterReadingHistory(models.Model):
    resident = models.ForeignKey(Resident)
    value = models.IntegerField(verbose_name=u"Значение",
        validators = [
            MinValueValidator(1)
        ])
    adding_date = models.DateField(default=datetime.now, verbose_name=u"Дата снятия показаний")
    meter_type = models.ForeignKey(MeterType)

    def __unicode__(self):
        return u"%s - %s" % (self.resident.last_name, self.value)


class Notification(models.Model):
    NOTIFICATIONS = (
        (0, u"Отключение воды"),
        (1, u"Отключение света"),
        (2, u"Собрание"),
        (3, u"Общее"),
    )
    NOTIFICATIONS_DICT = dict(NOTIFICATIONS)
    start_date = models.DateTimeField(verbose_name=u'Начиная с')
    end_date = models.DateTimeField(verbose_name=u'Заканчивая')
    text = models.TextField(verbose_name=u"Доп информация")
    note_type = models.IntegerField(choices=NOTIFICATIONS, default=3, verbose_name=u"Тип")
    houses = models.ManyToManyField(House)

templates/user/employer_request.html
{% extends "base.html" %}

{% block menu %}
{% include "user/menu.html" %}
{% endblock %}

{% block content %}

{% include "user/leftmenu.html" %}

<h2>Вызвать сотрудника</h2>

<div class="col-md-10">
	<form method = "post"  action="{% url "employer_request" %}" enctype="multipart/form-data"  class="form-horizontal" role="form">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	<div class="form-group {% if field.errors %}has-error{% endif %}">
		<label for="{{field.name}}" class="col-sm-3 control-label">
		{{field.label}}:
		</label>
		<div class="col-sm-4">
			{{field}}		
			<span class="help-block">
			{% if field.errors %}
				{% for error in field.errors %}
					{{error}}
				{% endfor %}
			{% endif %}
			</span>
		</div>
	</div>
	{% endfor %}
	<div class="form-group">
	<div class="col-sm-offset-3 col-sm-10">
		<label for="request_date">Когда должен прийти сотрудник</label>
	    <div class="input-group col-sm-3" >
	      <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
	      <input class="form-control" id="request_date" name="request_date" placeholder="введите дату">
	    </div>	
	</div>
	
	</div>
<div class="form-group">
	    <div class="col-sm-offset-3 col-sm-10">
	    	<button type="submit" class="btn btn-success">Записать</button>
	    </div>
	 </div>
	</form>
	<h2>История заявок</h2>
  {% if hist %}
  <table class="table">
   <thead>
   		<tr> 
   			<th>№</th>
   			{# <th>ФИО</th> #}
   			<th>Работник</th>
   			<th>Причина вызова</th>
   			<th>Статус</th>
   		</tr>
   </thead>
   <tbody>
   		{% for h in hist %}
      <tr>
   			<td>{{ forloop.counter }}</td>
   			<td>{{ h.employer.profession}}</td>
   			<td>{{h.reason}}</td>
   			<td>

   			{% if h.status %}
   				Одобрено
   			{% else %}
   				На рассмотрении
   			{% endif%}
   			</td>
   		{% endfor %}
      </tr>
   </tbody>
  </table>

  {% else %}
  	Нет заявок
  {% endif%}
</div>
{% endblock %}

{% block scripts %}
<script type="text/javascript">
$(function() {
  $( "#request_date" ).datepicker({
    defaultDate: "0",
    minDate:"0",
    altFormat: "yy-mm-dd",
    dateFormat: "yy-mm-dd",
    changeMonth: true,
    onClose: function( selectedDate ) {
      $( "#to" ).datepicker( "option", "minDate", selectedDate );
    }
  });
});
</script>
{% endblock %}

templates/user/home.html
{% extends "base.html" %}
{% block menu %}
{% include "user/menu.html" %}
{% endblock %}
{% block content %}
{% include "user/leftmenu.html" %}
<div class="col-md-10">
<div class="grid">
    <div class="col-md-3">
        <div class="bill positive">942,84  <i class="fa fa-rub"></i></div>
        <div class="date">Состояние на <strong>19.10.2014</strong></div>
        <div>120 <i class="fa fa-rub"></i> кВт/ч, 33 <i class="fa fa-rub"></i> м<sup>3</sup> </div>
    </div>
    <div class="col-md-1">
    </div>
    <div class="col-md-4">
        <div class="profile">
            <div class="name">{{org.get_company_type}} «{{org}}»</div>
            <div class="bill_numb">тел.: {{org.phone}}</div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="profile">
            <div class="name">{{resident.first_name}} {{resident.last_name}} (кв. {{resident.flat}})</div>
            <div class="bill_numb">Л/C №{{resident.bill_numb}}</div>
            <div><a href="{% url "userprofile" %}">Профиль</a></div>
        </div>
    </div>
    <div class="col-md-12">
        <p><span class="demo light">Нет света</span> <span class="demo water">Нет воды</span></p>
        <ul class="week">
            {% for item in calendar %}
            <li class="{% for event in item.events %}{% if event.note_type == 0%}nowater {% elif event.note_type == 1%}nolight{% endif %}{% endfor %}{% if item.dayofweek == "СБ" or item.dayofweek == "ВС" %} weekend{% endif %}">
                <div class="dayofweek">{{item.dayofweek}}</div>
                <div class="day">
                    {% if item.events %}
                    <a href="#" class="pop" data-toggle="popover"  data-trigger="hover" data-placement="bottom" title="События" data-content="{% for event in item.events %}<strong>{{event.get_note_type_display}}:</strong> {{event.text}}<br>{% endfor %}" data-html="true" style="white-space: nowrap;">{{item.date.day}}</a>
                    {% else %}
                    {{item.date.day}}
                    {% endif %}
                </div>
            </li>
            {% endfor %}
        </ul>
        {% for note in notifications %}
        <div class="note">
            <div class="date">{{note.pub_date|date:"j E"}}, <nobr>{{note.pub_date|date:"Y"}}</nobr></div>
            {{note.text}}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$('.pop').popover();
</script>
{% endblock %}

templates/user/leftmenu.html
<div class="col-md-2">
<ul class="nav nav-pills nav-stacked">
    <li class="inacvtive">Лицевой счет</li>
    <li><a href="{% url "employer_request" %}">Вызов служб</a></li>
    <li><a href="{% url "meter" %}">Показания счетчика</a></li>
    <li class="inacvtive">Инфо о ТСЖ организации </li>
    <li class="inacvtive">Оповещения жильцов </li>
    <li class="inacvtive"><div class="pull-right"><span class="label label-success">2</span></div>Сводка событий</li>
</ul>
</div>

templates/user/menu.html
<nav class="navbar navbar-default" role="navigation">
    <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url "home" %}">House Management</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li {% if current_url == "home" %} class="active" {% endif %}><a href="{% url "home" %}">Панель управления</a></li>
                <li {% if current_url == "userprofile" %} class="active" {% endif %}><a href="{% url "userprofile" %}">Профиль</a></li>
                <li ><a href="{% url "logoutview" %}">Выход</a></li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

templates/user/meter_reading.html
{% extends "base.html" %}

{% block menu %}
{% include "user/menu.html" %}
{% endblock %}

{% block scripts %}
 
  <script type="text/javascript">
    $(".btn-success").click(function() {
      if (!confirm('Вы уверены, что хотите внести показания?')) 
        return false;
    })

    var chartData = [];
    {% for key, value in chart_data.iteritems %}       
     chartData[{{key}}] = [
        {% for h in value %}
          {
             "date": "{{h.adding_date.isoformat}}",
            "value": {{h.value}}
          },
        {% endfor%}
      ];
    {% endfor%}

    var chart = AmCharts.makeChart("chartdiv", {
        "type": "serial",
        "theme": "patterns",
        "pathToImages": "http://www.amcharts.com/lib/3/images/",
        "dataDateFormat": "YYYY-MM-DD",
        "valueAxes": [{
            "id":"v1",
            "axisAlpha": 0,
            "position": "left"
        }],
        "graphs": [{
      "id": "g1",
            "bullet": "round",
            "bulletBorderAlpha": 1,
            "bulletColor": "#FFFFFF",
            "bulletSize": 5,
            "hideBulletsCount": 50,
            "lineThickness": 2,
            "title": "red line",
            "useLineColorForBulletBorder": true,
            "valueField": "value"
        }],
        "chartScrollbar": {
      "graph": "g1",
      "scrollbarHeight": 30
    },
        "chartCursor": {
            "cursorPosition": "mouse",
            "pan": true,
             "valueLineEnabled":true,
             "valueLineBalloonEnabled":true
        },
        "categoryField": "date",
        "categoryAxis": {
            "parseDates": true,
            "dashLength": 1,
            "minorGridEnabled": true,
            "position": "bottom"
        },
        exportConfig:{
          menuRight: '20px',
          menuBottom: '50px',
          menuItems: [{
          icon: 'http://www.amcharts.com/lib/3/images/export.png',
          format: 'png'   
          }]  
        },
        "dataProvider": chartData[1],
    }
  );


chart.dataProvider = chartData[1];
chart.addListener("rendered", zoomChart);
function selectDataset(d) {
    chart.dataProvider = chartData[d];
    chart.validateData();
    chart.animateAgain();
}

zoomChart();
function zoomChart(){
    chart.zoomToIndexes(chart.dataProvider.length - 10, chart.dataProvider.length - 1);
}

  </script>
{% endblock %}

{% block content %}

{% include "user/leftmenu.html" %}

	<h2>Ввод показаний</h2>
	<div class="col-md-10">
  <div class="jumbotron">
    {% if need %}
      <div class="alert alert-info" role="alert">
      
      <h4>В этом месяце вам осталось заполнить:</h4>
      <p>
        <ul>
          {% for n in need %}
          <li>
          {{n}}
          </li>
          {% endfor %}
        </ul>
      </p>
    </div>  
		<form method = "post"  action="{% url "meter" %}" enctype="multipart/form-data"  class="form-horizontal" role="form">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	<div class="form-group {% if field.errors %}has-error{% endif %}">
		<label for="{{field.name}}" class="col-sm-3 control-label">{{field.label}}:</label>
		<div class="col-sm-4">
			{{field}}		<span class="help-block">{% if field.errors %}{% for error in field.errors %}{{error}}{% endfor %}{% endif %}</span>

		</div>
	</div>
	{% endfor %}
	 <div class="form-group">
	    <div class="col-sm-offset-3 col-sm-10">
	    	<button type="submit" class="btn btn-success">Ввести</button>
	    </div>
	 </div>
	</form>
      {% else %}
        <div class="alert alert-success" role="alert">
           Вы заполнили показания за этот месяц
        </div>
      {% endif %}
      </div>
  <h2>История показаний</h2>
  {% if hist %}
  <table class="table">
   <thead>
   		<tr> 
   			<th>№</th>
   			{# <th>ФИО</th> #}
   			<th>Тип</th>
   			<th>Значение</th>
   			<th>Дата</th>
   		</tr>
   </thead>
   <tbody>
   		{% for h in hist %}
      <tr>
   			<td>{{ forloop.counter }}</td>
   			{# <td>{{h.resident.last_name}} {{h.resident.first_name}} {{h.resident.last_name}}</td> #}
   			<td>{{ h.meter_type.name}}</td>
   			<td>{{h.value}}</td>
   			<td>{{h.adding_date}}</td>
   		{% endfor %}
      </tr>
   </tbody>
  </table>
  <div class="panel panel-default">
  <div class="panel-heading">
    <div id="selector">Выберете счетчик:
    {% for m in meter_names %}
     <label>
      <input type="radio" value="{{m.id}}" name="dataset" onclick="selectDataset({{m.id}});"> {{m.name}}
      </label>
      {% endfor %}
    </div>
  </div>
  <div class="panel-body">
     <div id="chartdiv"></div>
  </div>
</div>
    

  {% else %}
  	Нет данных
  {% endif%}

</div>
	

{% endblock %}

templates/user/profile.html
{% extends "base.html" %}
{% block menu %}
{% include "user/menu.html" %}
{% endblock %}
{% block content %}
{% include "user/leftmenu.html" %}
<div class="col-md-10">
    <table class="table table-bordered">
    {% for field in profile %}
    {% if field.value %}
    <tr>
        <td>{{field.label}}</td>
        <td>{{field.value}}</td>
    </tr>
    {% endif %}
    {% endfor %}
    </table>
</div>
{% endblock %}

templates/user/registration.html
{% extends "base.html" %}
{% comment %}
	ФИО
	Л/С (реквизит квартиры)
	Доки (аттач: паспорт и прописка)
	Телефон
{% endcomment %}

{% block scripts %}
	<script type="text/javascript">
		$("form input, form textarea, form select").addClass("form-control");
		$('input[type=file]')
			.addClass("btn-primary")
			.attr('title', "Добавить документ")
			.attr('data-filename-placement', "inside")
			.bootstrapFileInput();
	</script>
{% endblock %}
{% block content %}

	<form method = "post"  action="{% url "register" %}" enctype="multipart/form-data"  class="form-horizontal" role="form">
	{% csrf_token %}
	{% for field in form.visible_fields %}
	<div class="form-group {% if field.errors %}has-error{% endif %}">
		<label for="{{field.name}}" class="col-sm-3 control-label">{{field.label}}:</label>
		<div class="col-sm-4">
			{{field}}		<span class="help-block">{% if field.errors %}{% for error in field.errors %}{{error}}{% endfor %}{% endif %}</span>

		</div>
	</div>
	{% endfor %}
	 <div class="form-group">
	    <div class="col-sm-offset-3 col-sm-10">
	    	<button type="submit" class="btn btn-success">Регистрация</button>
	    </div>
	 </div>
	</form>


{% endblock %}